export interface PopularJob {
    id:number,
    title:string,
    company:string,
    location:string,
    salary:string,
    description:string,
    url:string,
    date:string,
    source:string,
    tags:string[],
    logo?:string,
    logo_background_color:string,
    how_to_apply:string,
    company_url:string,
    type:string,
    created_at:string,
    apply_url:string,
    company_industry:string,
    company_size:string,
    company_founded:string,
    company_sector:string,
    company_twitter:string,
};

export interface RecentJob{
    id:number,
    title:string,
    company:string,
    location:string,
    salary:string,
    description:string,
    url:string,
    date:string,
    source:string,
    tags:string[],
    logo:string,
    logo_background_color:string,
    how_to_apply:string,
    company_url:string,
    type:string,
    created_at:string,
}

export interface Company{
    id:number,
    name:string,
    logo:string,
    description:string,
    website:string,
    twitter:string,
    linkedin:string,
    founded:string,
    industry:string,
    size:string,
    sector:string,
    type:string,
    headquarters:string,
    employees:number,
    
}

